INSERT INTO  `categories` (`categoryId`, `title`, `alias`, `foreword`, `content`, `orderNumber`, `parentCategoryId`, `statusId`) VALUES 
(5, 'Минисистемы', 'minisistemy', 'foreword', '', NULL, NULL, 1) ,
(6, 'Arcam', 'minisistemy__arcam2', 'foreword', '', NULL, 5, 1) ,
(7, 'B&W', 'minisistemy__b_w', 'foreword', '', NULL, 5, 1) ,
(8, 'Cambridge Audio', 'minisistemy__cambridge_audio', 'foreword', '', NULL, 5, 1) ,
(9, 'Denon', 'minisistemy__denon1', 'foreword', '', NULL, 5, 1) ,
(10, 'Elipson', 'minisistemy__elipson1', 'foreword', '', NULL, 5, 1) ,
(11, 'Harman/Kardon', 'minisistemy__harmankardon', 'foreword', '', NULL, 5, 1) ,
(12, 'Magnat', 'minisistemy__magnat', 'foreword', '', NULL, 5, 1) ,
(13, 'Marantz', 'minisistemy__marantz', 'foreword', '', NULL, 5, 1) ,
(14, 'Music Hall', 'minisistemy__music_hall2', 'foreword', '', NULL, 5, 1) ,
(15, 'McIntosh', 'minisistemy__mcintosh1', 'foreword', '', NULL, 5, 1) ,
(16, 'NAD', 'minisistemy__nad', 'foreword', '', NULL, 5, 1) ,
(17, 'Onkyo', 'minisistemy__onkyo', 'foreword', '', NULL, 5, 1) ,
(18, 'Tangent', 'minisistemy__tangent', 'foreword', '', NULL, 5, 1) ,
(19, 'Teac', 'minisistemy__teac', 'foreword', '', NULL, 5, 1) ,
(20, 'Yamaha', 'minisistemy__yamaha', 'foreword', '', NULL, 5, 1) ;
