INSERT INTO  `categories` (`categoryId`, `title`, `alias`, `foreword`, `content`, `orderNumber`, `parentCategoryId`, `statusId`) VALUES 
(5, 'СПЕЦИАЛЬНЫЕ ПРЕДЛОЖЕНИЯ', 'special_nye_predlozheniya', 'foreword', '', NULL, NULL, 1) ,
(6, 'Акустические системы', 'akusticheskie_sistemy', 'foreword', '', NULL, NULL, 1) ,
(7, 'Винил', 'vinil', 'foreword', '', NULL, NULL, 1) ,
(8, 'Инсталляционное оборудование', 'installyacionnoe_oborudovanie', 'foreword', '', NULL, NULL, 1) ,
(9, 'Кабельная продукция', 'kabelnaya_produkciya', 'foreword', '', NULL, NULL, 1) ,
(10, 'Караоке машины', 'karaoke_mashiny', 'foreword', '', NULL, NULL, 1) ,
(11, 'Комплекты Домашнего Кинотеатра', 'komplekty_domashnego_kinoteatra', 'foreword', '', NULL, NULL, 1) ,
(12, 'Кронштейны и Крепежи', 'kronshtejny_i_krepezhi', 'foreword', '', NULL, NULL, 1) ,
(13, 'Мебель для AV техники', 'mebel_dlya_av_tehniki', 'foreword', '', NULL, NULL, 1) ,
(14, 'Медиаплееры Dune', 'mediapleery_dune', 'foreword', '', NULL, NULL, 1) ,
(15, 'Минисистемы', 'minisistemy', 'foreword', '', NULL, NULL, 1) ,
(16, 'Мультирум', 'multiroom', 'foreword', '', NULL, NULL, 1) ,
(17, 'Наушники', 'naushniki', 'foreword', '', NULL, NULL, 1) ,
(18, 'Проекторы', 'proektory', 'foreword', '', NULL, NULL, 1) ,
(19, 'Проигрыватели Blu-ray и DVD', 'proigryvateli_blu-ray_i_dvd', 'foreword', '', NULL, NULL, 1) ,
(20, 'Проигрыватели CD/SACD', 'proigryvateli_cd_sacd', 'foreword', '', NULL, NULL, 1) ,
(21, 'Проигрыватели сетевые', 'proigryvateli_setevye', 'foreword', '', NULL, NULL, 1) ,
(22, 'Пульты Универсальные', 'pul_ty_universal_nye', 'foreword', '', NULL, NULL, 1) ,
(23, 'Ресиверы AV', 'resivery_av', 'foreword', '', NULL, NULL, 1) ,
(24, 'CD/DVD/Blu-ray - Ресиверы', 'cddvdblu-ray_-_resivery', 'foreword', '', NULL, NULL, 1) ,
(25, 'Сетевые Фильтры', 'setevye_filtry', 'foreword', '', NULL, NULL, 1) ,
(26, 'Телевизоры', 'televizory', 'foreword', '', NULL, NULL, 1) ,
(27, 'Телевизоры для ванной, Влагозащищенные', 'televizory_dlya_vannoj_vlagozawiwennye', 'foreword', '', NULL, NULL, 1) ,
(28, 'Тюнеры FM/AM', 'tyunery_fm_am', 'foreword', '', NULL, NULL, 1) ,
(29, 'Усилители/Ресиверы Стерео', 'usiliteli_resivery_stereo', 'foreword', '', NULL, NULL, 1) ,
(30, 'Экраны', 'krany', 'foreword', '', NULL, NULL, 1) ,
(31, 'iPod Плееры ', 'pleery_apple_ipod', 'foreword', '', NULL, NULL, 1) ,
(32, 'iPod Док станции', 'tovary_dlya_i-pod', 'foreword', '', NULL, NULL, 1) ,
(33, 'Статьи и Рекомендации', 'stati_i_rekomendacii', 'foreword', '', NULL, NULL, 1) ;
